# Generated by Django 3.2.19 on 2023-07-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='filed',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
