# Generated by Django 3.2.19 on 2023-07-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_login_filed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login',
            name='location',
        ),
    ]
