# Generated by Django 3.2.19 on 2023-07-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_patient', '0001_initial'),
        ('payment', '0002_auto_20230729_0715'),
        ('stor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_patient',
            name='patient',
        ),
        migrations.AlterField(
            model_name='drug_request',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='register_patient.register_patient'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='History_patient',
        ),
        migrations.DeleteModel(
            name='Register_Patient',
        ),
    ]
