# Generated by Django 3.2.19 on 2023-08-01 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_patient', '0004_alter_patient_history_doctor'),
        ('stor', '0002_auto_20230729_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_lab_temporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labs', models.CharField(blank=True, max_length=1000)),
                ('Patient_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_patient.register_patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lab_tase_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stor.labtestname')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resulut', models.CharField(max_length=1000)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stor.user_lab_temporary')),
            ],
        ),
    ]
