# Generated by Django 3.2.19 on 2023-08-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_patient', '0004_alter_patient_history_doctor'),
        ('stor', '0003_labresult_labtest_labtestname_user_lab_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_patient.register_patient'),
        ),
    ]
