# Generated by Django 3.2.19 on 2023-08-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0004_alter_labresult_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labresult',
            old_name='patient_name',
            new_name='Patient_name',
        ),
    ]
