# Generated by Django 3.2.19 on 2023-08-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0005_rename_patient_name_labresult_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='test_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
