# Generated by Django 3.2.19 on 2023-08-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0006_labresult_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='test_name',
        ),
    ]
