# Generated by Django 3.2.19 on 2023-07-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Doctor_Field', models.CharField(max_length=150)),
                ('Room', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Drug_Stor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_drug', models.CharField(default=None, max_length=100)),
                ('quantity_drugs', models.IntegerField(default=0)),
                ('price_per_drug', models.IntegerField(default=0)),
                ('descriptions_drug', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Register_Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Full_Name', models.CharField(max_length=200)),
                ('Father_Name', models.CharField(max_length=150)),
                ('Mother_Name', models.CharField(max_length=150)),
                ('Age', models.IntegerField(default=0)),
                ('Sex', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='None', max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Emergency_Phone_Number', models.CharField(max_length=15)),
                ('Birth_Day', models.DateField()),
                ('Created_at', models.DateTimeField(auto_now=True)),
                ('Nurse_Checked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['Created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescribe_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribe_time', models.DateTimeField(auto_now=True)),
                ('prescribe_medication', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_patient.register_patient')),
                ('prescribe_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_patient.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_text', models.TextField(max_length=100000000)),
                ('history_time', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_patient.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_patient.register_patient')),
            ],
        ),
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=700)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_patient.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_patient.register_patient')),
            ],
        ),
    ]
