# Generated by Django 3.2.19 on 2023-07-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_Stor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_drug', models.CharField(default=None, max_length=100)),
                ('quantity_drugs', models.IntegerField(default=0)),
                ('price_per_drug', models.IntegerField(default=0)),
                ('drug_receiver', models.CharField(default=None, max_length=100)),
                ('drug_hand_in', models.CharField(default=None, max_length=100)),
                ('descriptions_drug', models.TextField(max_length=1000)),
            ],
        ),
    ]
