# Generated by Django 3.2.19 on 2023-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug_stor',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
