# Generated by Django 3.2.19 on 2023-07-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0002_drug_stor_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug_stor',
            name='drug_hand_in',
        ),
        migrations.RemoveField(
            model_name='drug_stor',
            name='drug_receiver',
        ),
    ]
