# Generated by Django 3.2.19 on 2023-07-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0003_auto_20230724_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='drug_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency_phone_number', models.CharField(max_length=15)),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('drug_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register_Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField(default=0)),
                ('Sex', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='None', max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Emergency_Phone_Number', models.CharField(max_length=15)),
                ('Created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['Created_at'],
            },
        ),
    ]
