# Generated by Django 3.2.19 on 2023-07-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0004_drug_request_register_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug_stor',
            name='total_price',
        ),
    ]
