# Generated by Django 3.2.19 on 2023-07-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0005_remove_drug_stor_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug_request',
            name='address',
        ),
        migrations.RemoveField(
            model_name='drug_request',
            name='age',
        ),
        migrations.RemoveField(
            model_name='drug_request',
            name='emergency_phone_number',
        ),
        migrations.RemoveField(
            model_name='drug_request',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drug_request',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='drug_request',
            name='sex',
        ),
        migrations.AddField(
            model_name='drug_request',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stor.register_patient'),
        ),
    ]
