# Generated by Django 3.2.19 on 2023-07-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0006_auto_20230725_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name_Dr', models.CharField(max_length=50)),
                ('Last_name_Dr', models.CharField(max_length=50)),
                ('time_with_patient', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stor.register_patient')),
            ],
        ),
    ]
