# Generated by Django 3.2.19 on 2023-07-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0008_auto_20230725_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patient_history',
        ),
    ]
