# Generated by Django 3.2.19 on 2023-07-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0010_delete_history_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hisory_text', models.TextField(max_length=100000000)),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stor.register_patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient_history',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stor.history_patient'),
        ),
    ]
