# Generated by Django 3.2.19 on 2023-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0011_auto_20230725_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_patient',
            name='Sex',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=10),
        ),
    ]
