# Generated by Django 3.2.19 on 2023-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0012_alter_register_patient_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_patient',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
